### ISSUE TITLE
arduino stuck

### ISSUE THREAD

**Issue by robots** [hassebjork/WeatherReader#1]
Hi,

The problem with stuck arduino code is here:
https://github.com/hassebjork/WeatherReader/blob/master/arduino/WeatherReader/WeatherReader.ino#L371

You need to reset decoder when the checksum is not correct, otherwise it will hang forever.
`
if ( !decoder.checkSum() ) {
decoder.resetDecoder();
return;
}
`

**Comment by hassebjork** [comment]
Thank you!

I trust your judgement, and updated the code although with two rows less of code ;)

I have not looked at this code in a few years, and my whole system has been working a few years, with nightly rebooting, until 2 months ago. I guess the Raspberry PI has broken down, and I have no time to fix it.
